# Use a specific Python version
FROM python:3.9.12

# Set working directory
WORKDIR /code

# Copy requirements file and install dependencies
COPY requirements.txt /code/
RUN pip install --no-cache-dir --upgrade -r requirements.txt

ENV DATABASE dsk
ENV HOST dsk_mysql
ENV USER dsk_admin
ENV PASSWORD dsk

# Copy the application code to the container
COPY . /code/

# Expose port for the application
EXPOSE 9090

# Default command to run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9090"]